// src/workoutDatabase.js
export const workoutDatabase = {
  Chest: [
    {
      name: "Barbell Bench Press",
      sets: 4,
      reps: "8",
      velocity: "1.0 m/s",
      estTime: 12,
    },
    {
      name: "Incline Dumbbell Press",
      sets: 3,
      reps: "10",
      velocity: "1.0 m/s",
      estTime: 10,
    },
    {
      name: "Dumbbell Fly",
      sets: 3,
      reps: "12",
      velocity: "0.8 m/s",
      estTime: 8,
    },
    {
      name: "Push Up",
      sets: 3,
      reps: "AMRAP",
      velocity: "Bodyweight",
      estTime: 8,
    },
  ],
  Core: [
    {
      name: "Hanging Knee Raises",
      sets: 3,
      reps: "15",
      velocity: "Controlled",
      estTime: 8,
    },
    {
      name: "Ab Wheel Rollouts",
      sets: 3,
      reps: "10",
      velocity: "Slow",
      estTime: 9,
    },
    {
      name: "Plank Hold",
      sets: 3,
      reps: "60s",
      velocity: "Static",
      estTime: 6,
    },
  ],
  Shoulders: [
    {
      name: "Overhead Barbell Press",
      sets: 4,
      reps: "8",
      velocity: "0.9 m/s",
      estTime: 12,
    },
    {
      name: "Dumbbell Lateral Raises",
      sets: 4,
      reps: "12-15",
      velocity: "1.2 m/s",
      estTime: 8,
    },
    {
      name: "Face Pulls",
      sets: 3,
      reps: "15",
      velocity: "1.0 m/s",
      estTime: 6,
    },
  ],
  Biceps: [
    {
      name: "Barbell Bicep Curls",
      sets: 4,
      reps: "10",
      velocity: "1.0 m/s",
      estTime: 10,
    },
    {
      name: "Hammer Curls",
      sets: 3,
      reps: "12",
      velocity: "1.1 m/s",
      estTime: 8,
    },
  ],
  Forearms: [
    {
      name: "Behind-the-Back Wrist Curls",
      sets: 3,
      reps: "15",
      velocity: "Controlled",
      estTime: 6,
    },
    {
      name: "Farmer's Walks",
      sets: 3,
      reps: "45s",
      velocity: "Heavy Hold",
      estTime: 8,
    },
  ],
  Quadriceps: [
    {
      name: "Barbell Back Squats",
      sets: 4,
      reps: "6-8",
      velocity: "0.8 m/s",
      estTime: 15,
    },
    {
      name: "Leg Press",
      sets: 3,
      reps: "10",
      velocity: "0.9 m/s",
      estTime: 10,
    },
    {
      name: "Leg Extensions",
      sets: 3,
      reps: "15",
      velocity: "1.2 m/s",
      estTime: 6,
    },
  ],
  Trapezius: [
    {
      name: "Barbell Shrugs",
      sets: 4,
      reps: "12",
      velocity: "0.8 m/s",
      estTime: 10,
    },
    { name: "Rack Pulls", sets: 3, reps: "6", velocity: "Heavy", estTime: 10 },
  ],
  Lats: [
    {
      name: "Wide-Grip Pull Ups",
      sets: 4,
      reps: "8",
      velocity: "Bodyweight",
      estTime: 10,
    },
    {
      name: "Barbell Bent Over Rows",
      sets: 3,
      reps: "8",
      velocity: "1.0 m/s",
      estTime: 9,
    },
  ],
  "Lower Back": [
    {
      name: "Barbell Good Mornings",
      sets: 3,
      reps: "10",
      velocity: "Slow",
      estTime: 9,
    },
    {
      name: "Hyperextensions",
      sets: 3,
      reps: "15",
      velocity: "Controlled",
      estTime: 7,
    },
  ],
  Triceps: [
    {
      name: "Close-Grip Bench Press",
      sets: 3,
      reps: "8",
      velocity: "1.0 m/s",
      estTime: 10,
    },
    {
      name: "Cable Tricep Pushdowns",
      sets: 4,
      reps: "12",
      velocity: "1.2 m/s",
      estTime: 8,
    },
  ],
  Glutes: [
    {
      name: "Barbell Hip Thrusts",
      sets: 4,
      reps: "8-10",
      velocity: "0.9 m/s",
      estTime: 12,
    },
    {
      name: "Romanian Deadlifts",
      sets: 3,
      reps: "10",
      velocity: "0.8 m/s",
      estTime: 10,
    },
  ],
  Hamstrings: [
    {
      name: "Lying Leg Curls",
      sets: 4,
      reps: "10",
      velocity: "1.0 m/s",
      estTime: 8,
    },
    {
      name: "Glute-Ham Raises",
      sets: 3,
      reps: "8",
      velocity: "Bodyweight",
      estTime: 9,
    },
  ],
  Calves: [
    {
      name: "Standing Calf Raises",
      sets: 4,
      reps: "15",
      velocity: "Explosive",
      estTime: 8,
    },
  ],
};

export const secondaryMuscleMap = {
  Chest: "Anterior Deltoids, Triceps",
  Core: "Obliques, Transverse Abdominis",
  Shoulders: "Triceps, Upper Trapezius",
  Biceps: "Forearms, Brachialis",
  Forearms: "Brachioradialis, Grip Dynamics",
  Quadriceps: "Glutes, Adductors",
  Trapezius: "Rear Deltoids, Rhomboids",
  Lats: "Biceps, Rhomboids, Rear Deltoids",
  "Lower Back": "Glutes, Hamstrings",
  Triceps: "Anterior Deltoids, Chest Tie-ins",
  Glutes: "Hamstrings, Erector Spinae",
  Hamstrings: "Glutes, Calves",
  Calves: "Soleus, Gastrocnemius",
};
